@port = 5000
@baseURL = http://127.0.0.1:{{port}}/api

##################################### USERS #####################################
### GET /users
GET {{baseURL}}/users

### POST /users
POST {{baseURL}}/users
Content-Type: application/json

{
    "email": "lololol@gmail.com",
    "password": "aeap19980929",
    "firstname": "cris",
    "lastname": "Herrera"
}

### PUT /users/:id
PUT {{baseURL}}/users/536c9c21-f9e9-46be-a84f-4a8fb7b45cc2
Content-Type: application/json

{
    "email": "otro@gmail.com"
}

### DELETE /users/:id
DELETE {{baseURL}}/users/536c9c21-f9e9-46be-a84f-4a8fb7b45cc2

##################################### PROFILES #####################################
### GET /profiles
GET {{baseURL}}/profiles/85ba83d2-9b9f-4c15-8b88-fc752dbdb634

### POST /profiles
POST {{baseURL}}/profiles
Content-Type: application/json

{
    "gender": "MALE",
    "dni": "AAPA980929HYNLCD05",
    "phone": "9991549015",
    "birthday": "1998/09/29",
    "address": "C94A #857 x139 y 141 Merida,Yucatan",
    "user_id": "4d9521a8-4413-4f22-826c-ff22f2e6e0e0"
}

### PUT /profiles/:id
PUT {{baseURL}}/profiles/6d67f6b3-4cf1-4f4f-bebd-58f4eca45fd1
Content-Type: application/json

{
    "phone": "9995549015"
}

### DELETE /profiles/:id
DELETE {{baseURL}}/profiles/6d67f6b3-4cf1-4f4f-bebd-58f4eca45fd1

##################################### EXPENSES #####################################
### GET /profiles
GET {{baseURL}}/expenses

### POST /expenses
POST {{baseURL}}/expenses
Content-Type: application/json

{
    "name": "Compra de lo que sea",
    "description": "vasrvsd",
    "date": "2021/03/01",
    "total": "243425"
}

### PUT /expenses/:id
PUT {{baseURL}}/expenses/1c70e39b-7cc2-4ca5-b49f-e6c176afd462
Content-Type: application/json

{
    "description": "compre algo"
}

### DELETE /expenses/:id
DELETE {{baseURL}}/expenses/1c70e39b-7cc2-4ca5-b49f-e6c176afd462