@port = 5000
@baseURL = http://127.0.0.1:{{port}}/api
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjMwMzA1NjYsImlkIjoiNGY2MWE4YTItODE1Ny00ZGI1LTg1ODAtYTZjNDJmMjUxZGUyIiwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFhveUxOSy9wbHBUaDBxcGoxdTJhWU9ldEV0ZHVNcWhRL282QWVXck50WmpBYTJYMzFDaDhLIiwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IlVzZXIiLCJyb2xlIjoiQURNSU4iLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMS0wNi0wNlQxNzo1MzowOC44NzdaIiwidXBkYXRlZEF0IjoiMjAyMS0wNi0wNlQxNzo1MzowOC44NzdaIiwiaWF0IjoxNjIzMDI2OTY2fQ.o4qnjZFTEAkB4P3yEOdbWrw2IKGWcVXd2mbVGvHoxIQ

### GET /providers
GET {{baseURL}}/providers
Authorization: Bearer {{access_token}}

### POST /providers
POST {{baseURL}}/providers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Nestle",
    "address": "C 94a",
    "country": "Mexico",
    "city": "Merida",
    "state": "Yucatan",
    "phone": "9993428913",
    "email": "contact@nestle.com",
    "notes": "Proveedor importante",
    "contactName": "Jose Perez"
}

### GET /categories
GET {{baseURL}}/categories
Authorization: Bearer {{access_token}}

### POST /categories
POST {{baseURL}}/categories
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Enlatados",
    "description": "Productos en lata"
}

### GET /products
GET {{baseURL}}/products
Authorization: Bearer {{access_token}}

### POST /products
POST {{baseURL}}/products
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Atun",
    "providerId": "f9cd3675-80fd-4ce0-ad60-bc30b56311a6",
    "categoryId": "4db99568-f392-495c-904c-1dd8a628cc93",
    "price": "14",
    "code": "5476509864",
    "description": "Atun en agua",
    "cost": "10",
    "min": "10",
    "max": "20",
    "status": "ACTIVE",
    "image": "http://imagenes.com/2341"
}
### GET /buy-orders
GET {{baseURL}}/buy-orders
Authorization: Bearer {{access_token}}

### POST /buy-orders
POST {{baseURL}}/buy-orders
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "date": "2021/03/01",
    "status": "DUE"
}

### GET /buys
GET {{baseURL}}/buys
Authorization: Bearer {{access_token}}

### POST /buys
POST {{baseURL}}/buy-orders/399709e2-d790-4e99-a912-8edc4eaa5e3f/buys
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "items": [{
        "productId": "7ec70c64-a8de-42e8-8a8c-93bb648f0972",
        "quantity": 20
    }]
}

### GET /inventories
GET {{baseURL}}/inventories
Authorization: Bearer {{access_token}}

### GET /sales
GET {{baseURL}}/sales

### POST /sales
POST {{baseURL}}/sale-orders/913ad2a9-89d1-4fc2-b09d-d47151f72e06/sales
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "items": [
        {
            "quantity": 10,
            "productId": "3c1b99ba-a7ab-42fd-aa1c-5fd32f7b5ffd"
        }
    ]
}

##################################### sale-orders #####################################
### GET /sale-orders
GET {{baseURL}}/sale-orders/
Authorization: Bearer {{access_token}}

### POST /sale-orders
POST {{baseURL}}/sale-orders
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "date": "2021/03/12",
    "status": "DUE"
}