@port = 5000
@baseURL = http://127.0.0.1:{{port}}/api
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjI5NDc3MjgsImlkIjoiMGZlYmZlZjMtYjE5OS00MWUzLTk3NjgtNDNlNDM2M2YwNWFhIiwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJC9sM1RXamRFcWpjWkdvbHFLZy5UMS5IbXZhby81Y3VVQ2I3bjN3VGRBZHR1Qy5yLzBld0lDIiwiZmlyc3RuYW1lIjoiQWRtaW4iLCJsYXN0bmFtZSI6IlVzZXIiLCJyb2xlIjoiQURNSU4iLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMS0wNi0wNlQwMjoyMDoyNC40NzZaIiwidXBkYXRlZEF0IjoiMjAyMS0wNi0wNlQwMjoyMDoyNC40NzZaIiwiaWF0IjoxNjIyOTQ2ODI4fQ.ZHDHJJ2msK9ptm-bLJVm3ekWyX7q7oHPlsOFHjqlZu8

##################################### USERS #####################################
### GET /users
GET {{baseURL}}/users
Authorization: Bearer {{access_token}}

### POST /users
POST {{baseURL}}/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "email": "aeap@gmail.com",
    "password": "12345678",
    "firstname": "Adolfo",
    "lastname": "Alvarez"
}

### POST /auth/signin
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin_34632"
}

### POST /auth/signin
POST {{baseURL}}/auth/signin
Content-Type: application/json

{
    "email": "adolfo@gmail.com",
    "password": "12345678"
}

### PUT /users/:id
PUT {{baseURL}}/users/11ee22c9-2c9c-4159-aa8f-2ee4c4f4ee76
Content-Type: application/json

{
    "firstname": "Esteban"
}

### DELETE /users/:id
DELETE {{baseURL}}/users/11ee22c9-2c9c-4159-aa8f-2ee4c4f4ee76

##################################### PROFILES #####################################
### GET /profiles
GET {{baseURL}}/profiles/8e8ac86e-7932-4850-9d27-654569a14358

### POST /profiles
POST {{baseURL}}/profiles
Content-Type: application/json

{
    "gender": "MALE",
    "dni": "AAPA980929HYNLCD03",
    "phone": "9991549015",
    "birthday": "1998/09/29",
    "address": "C94A #857 x139 y 141 Merida,Yucatan",
    "user_id": "3fccab42-b378-4ddc-b8fc-bad803289598"
}

### PUT /profiles/:id
PUT {{baseURL}}/profiles/8e8ac86e-7932-4850-9d27-654569a14358
Content-Type: application/json

{
    "phone": "9995549015"
}

### DELETE /profiles/:id
DELETE {{baseURL}}/profiles/6d67f6b3-4cf1-4f4f-bebd-58f4eca45fd1

##################################### EXPENSES #####################################
### GET /profiles
GET {{baseURL}}/expenses

### POST /expenses
POST {{baseURL}}/expenses
Content-Type: application/json

{
    "name": "Compra de lo que sea",
    "description": "vasrvsd",
    "date": "2021/03/01",
    "total": "243425"
}

### PUT /expenses/:id
PUT {{baseURL}}/expenses/1c70e39b-7cc2-4ca5-b49f-e6c176afd462
Content-Type: application/json

{
    "description": "compre algo"
}

### DELETE /expenses/:id
DELETE {{baseURL}}/expenses/1c70e39b-7cc2-4ca5-b49f-e6c176afd462

##################################### buy-orders #####################################
### GET /buy-orders
GET {{baseURL}}/buy-orders

### POST /buy-orders
POST {{baseURL}}/buy-orders
Content-Type: application/json

{
    "providerId": "608e7b24-0d9b-4cef-8520-60c8a18155f0",
    "date": "2021/03/01",
    "status": "DUE"
}

### PUT /buy-orders/:id
PUT {{baseURL}}/buy-orders/80b3cd44-6a4b-49e4-951e-152815ee7d45
Content-Type: application/json

{
    "status": "CANCELED"
}

### DELETE /buy-orders/:id
DELETE {{baseURL}}/buy-orders/80b3cd44-6a4b-49e4-951e-152815ee7d45

##################################### buys #####################################
### GET /buys
GET {{baseURL}}/buys

### POST /buys
POST {{baseURL}}/buy-orders/4eaaf6c5-947d-4d15-aecc-e3f289a8fa6a/buys
Content-Type: application/json

{
    "items": [{
        "productId": "bbfaca16-b2ee-4c45-a55b-d378bfc8ff9b",
        "quantity": 2,
        "expiration": "2021-07-03T02:02:46.945Z"
    },
    {
        "productId": "bbfaca16-b2ee-4c45-a55b-d378bfc8ff9b",
        "quantity": 3,
        "expiration": "2021-07-05T02:02:46.945Z"
    }]
}

### PUT /buys/:id
PUT {{baseURL}}/buys/18d6c282-3d3d-4cc8-b4b5-72e6d5b761d8
Content-Type: application/json

{
    "quantity": "12"
}

### DELETE /buys/:id
DELETE {{baseURL}}/buys/18d6c282-3d3d-4cc8-b4b5-72e6d5b761d8

##################################### categories #####################################
### GET /categories
GET {{baseURL}}/categories

### POST /categories
POST {{baseURL}}/categories
Content-Type: application/json

{
    "name": "Enlatados",
    "description": "Productos en lata"
}

### PUT /categories/:id
PUT {{baseURL}}/categories/2f2fedd7-7830-452c-b380-8a063d315509
Content-Type: application/json

{
    "description": "Productos enlatados"
}

### DELETE /categories/:id
DELETE {{baseURL}}/categories/2f2fedd7-7830-452c-b380-8a063d315509

##################################### inventories #####################################
### GET /inventories
GET {{baseURL}}/inventories

### PUT /inventories/:id
PUT {{baseURL}}/inventories/2f2fedd7-7830-452c-b380-8a063d315509
Content-Type: application/json

{
    "description": "Productos enlatados"
}

### DELETE /inventories/:id
DELETE {{baseURL}}/inventories/2f2fedd7-7830-452c-b380-8a063d315509

##################################### products #####################################
### GET /products
GET {{baseURL}}/products

### POST /products
POST {{baseURL}}/products
Content-Type: application/json

{
    "name": "Cafe",
    "providerId": "608e7b24-0d9b-4cef-8520-60c8a18155f0",
    "categoryId": "518646dd-4ac7-43f7-a22a-87a79cd2f497",
    "price": "100",
    "code": "5476509864",
    "description": "Cafe negro",
    "cost": "95",
    "min": "10",
    "max": "20",
    "status": "ACTIVE",
    "image": "http://imagenes.com/2341"
}

### PUT /products/:id
PUT {{baseURL}}/products/e2c68283-0a9c-4093-9c12-4ac604fe0063
Content-Type: application/json

{
    "image": "http://imagenes.com/2342"
}

### DELETE /products/:id
DELETE {{baseURL}}/products/e2c68283-0a9c-4093-9c12-4ac604fe0063

##################################### providers #####################################
### GET /providers
GET {{baseURL}}/providers

### POST /providers
POST {{baseURL}}/providers
Content-Type: application/json

{
    "name": "Nestle",
    "address": "C 94a",
    "country": "Mexico",
    "city": "Merida",
    "state": "Yucatan",
    "phone": "9993428913",
    "email": "contact@nestle.com",
    "notes": "Proveedor importante",
    "contactName": "Jose Perez"
}

### PUT /providers/:id
PUT {{baseURL}}/providers/cb1cfc13-cf21-4fd6-8c83-e6356dc46003
Content-Type: application/json

{
    "city": "Uman"
}

### DELETE /providers/:id
DELETE {{baseURL}}/providers/cb1cfc13-cf21-4fd6-8c83-e6356dc46004

##################################### sales #####################################
### GET /sales
GET {{baseURL}}/sales

### POST /sales
POST {{baseURL}}/sales
Content-Type: application/json

{
    "saleOrderId": "2f2fedd7-7830-452c-b380-8a063d315509",
    "productId": "93283111-bf87-4d36-8b99-b6f679b3ef4a",
    "quantity": "3",
    "total": "100",
    "discount": "0"
}

### PUT /sales/:id
PUT {{baseURL}}/sales/89ed0226-9a81-48ec-8611-9e0e3b9c0d1a
Content-Type: application/json

{
    "quantity": "2"
}

### DELETE /sales/:id
DELETE {{baseURL}}/sales/89ed0226-9a81-48ec-8611-9e0e3b9c0d1a

##################################### sale-orders #####################################
### GET /sale-orders
GET {{baseURL}}/sale-orders/15dcdc5e-501f-4407-b39b-19a79e3f06e2

### POST /sale-orders
POST {{baseURL}}/sale-orders
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "totalSale": "100",
    "tax": "16",
    "date": "2021/03/12",
    "status": "DUE"
}

### PUT /sale-orders/:id
PUT {{baseURL}}/sale-orders/15dcdc5e-501f-4407-b39b-19a79e3f06e2
Content-Type: application/json

{
    "status": "PAID"
}

### DELETE /sale-orders/:id
DELETE {{baseURL}}/sale-orders/15dcdc5e-501f-4407-b39b-19a79e3f06e2