module.exports = {
  SERVER_PORT: 'SERVER_PORT',
  DB_HOST: 'DB_HOST',
  DB_USER: 'DB_USER',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  DB_PORT: 'DB_PORT',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXP_REFRESH_TKN: 'JWT_EXP_REFRESH_TKN',
  JWT_EXP_ACCESS_TKN: 'JWT_EXP_ACCESS_TKN',
  BCRYPT_HASH_ROUND: 'BCRYPT_HASH_ROUND'
}
